Diseño Pantalla Tasks
TeifitV/ProyectoFinal pull request #1
Opened 2019-03-30 23:27 UTC by Poble04

Cambia el TaskList y el TaskItem
Se añade fecha al TaskItem
Cambian los estilos del TaskList y del TaskItem
Se añade fecha a las tareas

2019-04-01 20:45 UTC, jaycorpstudios requested changes
Deje algunos comentarios, por favor borra el código que dejaste comentado en todos los archivos. 

NOTA: No olvides agregar el nombre de ticket o branch como prefijo en el mensaje de cada commit.

2019-04-01 20:45 UTC, jaycorpstudios commented on src/theme/colors.js
> +  dateColor: '#ED184A',
Todos los valores los estamos guardando en rgb. Puedes obtener esos valores en InVision.

2019-04-01 20:45 UTC, jaycorpstudios commented on src/shared/Helper.js
> +  formatDate(date, renderHoursAndMinutes = true){
Se que estas reusando lógica del otro proyecto, pero ya que esto sólo lo estas usando en TaskItem, deberías actualizar este método para que sólo te retorne el mes en el formato adecuado: "JAN", "FEB", "MAR", "APR", etc.

Si crees que este método se va a utilizar en mas lugares, tus compañeros de equipo deberían estar al tanto para que lo puedan usar, y entonces deberías crear otro método para que sólo te regrese el mes.

2019-04-01 20:45 UTC, jaycorpstudios commented on src/components/TasksList/tasksListStyle.js
> +    backgroundColor: '#F0F0F0'
Siempre usa los valores del Theme `theme/colors.js`, ya que si necesitamos actualizar algún color tendremos una sola fuente de verdad.

2019-04-01 20:45 UTC, jaycorpstudios commented on src/components/TaskItem/index.js
> +    //const icon = completed ? require('./../../images/icon-checked.png') : require('./../../images/icon-circle.png');
Borra el código comentado, si no es útil no lo necesitamos.

2019-04-01 20:45 UTC, jaycorpstudios commented on src/components/TaskItem/index.js
> +    const styleText = completed ? styles.checked : styles.title;
`styles.checked` me hace sentido, sin embargo `styles.title` no me hace sentido (el nombre de la propiedad) podría ser `unchecked`

2019-04-01 20:45 UTC, jaycorpstudios commented on src/components/TaskItem/index.js
> +    //date = (date === null) ? 1508770800000 : date;
Cualquier comment que no sea útil hay que borrarlo, también el console.log que esta en la línea 21, (se que tu no lo agregaste pero no se por que se quedó ahi.)

2019-04-04 18:52 UTC, jaycorpstudios requested changes
@Poble04  no se por que tienes tantos cambios innecesarios en tu PR, No tienes por que modificar archivos como el de .travis.yml, README.md, etc. Si lo que estas haciendo es copiar archivos de otro proyecto eso es un grave error.

Por favor corrige todos los comentarios que te deje.

2019-04-04 18:52 UTC, jaycorpstudios commented on app.json
> +    "name": "ProyectoFinal",
Por que tienes estos cambios si no tienen nada que ver con tu ticket?

2019-04-04 18:52 UTC, jaycorpstudios commented on package.json
> -    "test": "jest"
por que estas modificando esto?

2019-04-04 18:52 UTC, jaycorpstudios commented on package.json
> -  "jest": {
por que borras esta configuración?

2019-04-04 18:52 UTC, jaycorpstudios commented on src/shared/Constants.js
> +    months: ['ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DIC' ]
Estos meses deberían estar en ingles

2019-04-04 18:52 UTC, jaycorpstudios commented on src/shared/Helper.js
> +  formatDate(date, renderHoursAndMinutes = false){
Para que necesitas este helper?

2019-04-04 18:52 UTC, jaycorpstudios commented on src/theme/colors.js
> +  dateColor: 'rgb(237,24,74)',
te das cuenta que estas repitiendo colores?

2019-04-04 19:02 UTC, Poble04 commented
Creo que es el el primero que hice mal. ¿Recuerda que en clase me dijo cómo
corregirlo con un Cherry pick?

Después hice el push haciendo un pull y cambiando de branch y verificando
los cambios manualmente

On Thu, Apr 4, 2019, 12:52 PM Juan José Benítez (Jay) <
notifications@github.com> wrote:

> *@jaycorpstudios* requested changes on this pull request.
>
> @Poble04 <https://github.com/Poble04> no se por que tienes tantos cambios
> innecesarios en tu PR, No tienes por que modificar archivos como el de
> .travis.yml, README.md, etc. Si lo que estas haciendo es copiar archivos de
> otro proyecto eso es un grave error.
>
> Por favor corrige todos los comentarios que te deje.
> ------------------------------
>
> In app.json
> <https://github.com/TeifitV/ProyectoFinal/pull/1#discussion_r272317810>:
>
> > @@ -1,7 +1,7 @@
>
>  {
>
>    "expo": {
>
> -    "name": "RemindMe2Expo",
>
> -    "slug": "RemindMe2Expo",
>
> +    "name": "ProyectoFinal",
>
>
> Por que tienes estos cambios si no tienen nada que ver con tu ticket?
> ------------------------------
>
> In package.json
> <https://github.com/TeifitV/ProyectoFinal/pull/1#discussion_r272317895>:
>
> > @@ -4,24 +4,16 @@
>
>      "start": "expo start",
>
>      "android": "expo start --android",
>
>      "ios": "expo start --ios",
>
> -    "eject": "expo eject",
>
> -    "test": "jest"
>
>
> por que estas modificando esto?
> ------------------------------
>
> In package.json
> <https://github.com/TeifitV/ProyectoFinal/pull/1#discussion_r272317974>:
>
> >    },
>
>    "devDependencies": {
>
> -    "babel-preset-expo": "^5.0.0",
>
> -    "jest-expo": "^32.0.0"
>
> -  },
>
> -  "jest": {
>
>
> por que borras esta configuración?
> ------------------------------
>
> In src/shared/Constants.js
> <https://github.com/TeifitV/ProyectoFinal/pull/1#discussion_r272318159>:
>
> > @@ -0,0 +1,4 @@
>
> +export default constants = {
>
> +    months: ['ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DIC' ]
>
>
> Estos meses deberían estar en ingles
> ------------------------------
>
> In src/shared/Helper.js
> <https://github.com/TeifitV/ProyectoFinal/pull/1#discussion_r272318251>:
>
> > @@ -0,0 +1,22 @@
>
> +import constants from './Constants';
>
> +
>
> +export default class Helper{
>
> +
>
> +  formatDate(date, renderHoursAndMinutes = false){
>
>
> Para que necesitas este helper?
> ------------------------------
>
> In src/theme/colors.js
> <https://github.com/TeifitV/ProyectoFinal/pull/1#discussion_r272318420>:
>
> > @@ -6,5 +6,9 @@ export default colors = {
>
>    gray: 'rgb(164, 164, 164)',
>
>    separator: 'rgb(231,231,231)',
>
>    touchableHover: 'rgba(0,0,0,.05)',
>
> -  primaryText: 'rgb(29,29,38)'
>
> +  primaryText: 'rgb(29,29,38)',
>
> +  dateColor: 'rgb(237,24,74)',
>
>
> te das cuenta que estas repitiendo colores?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TeifitV/ProyectoFinal/pull/1#pullrequestreview-222941575>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ApcXFw9qdQ5gPYxz7sDUMcUzQ3LS7HfVks5vdknwgaJpZM4cUBcC>
> .
>

2019-04-04 19:09 UTC, jaycorpstudios commented
@Poble04 los errores que tienes en esos archivos es por que estas intercambiando archivos de otro proyecto con este (EXPO/NATIVE), las configuraciones son diferentes.

Por favor no hagas eso.

Regresa los cambios a como estaban antes del último commit. Y termina de arreglar los comentarios que te deje para que puedas hacer merge de este PR.

2019-04-04 22:08 UTC, Poble04 commented
Buen día profesor

Acabo de hacer un nuevo push llamadado "Cambios de opacidad"

Para ese push lo que hice fue hacer un clone de "develop" y ahí pegar mi
carpeta "src" con los cambios que hice; no cree un proyecto nuevo como lo
estaba haciendo.
Vi que si había archivos .json modificados, pero a esos le descartar
cambios con  "git checkout -- <file>..."

También cambié el color del texto de la tarea realizada, no me había
percatado de que no cambiaba de color.

El jue., 4 de abr. de 2019 a la(s) 13:09, Juan José Benítez (Jay) (
notifications@github.com) escribió:

> @Poble04 <https://github.com/Poble04> los errores que tienes en esos
> archivos es por que estas intercambiando archivos de otro proyecto con este
> (EXPO/NATIVE), las configuraciones son diferentes.
>
> Por favor no hagas eso.
>
> Regresa los cambios a como estaban antes del último commit. Y termina de
> arreglar los comentarios que te deje para que puedas hacer merge de este PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TeifitV/ProyectoFinal/pull/1#issuecomment-480025493>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ApcXF1gploMSLVbX6PK-PRuhOtD5liIVks5vdk3igaJpZM4cUBcC>
> .
>

2019-04-05 02:41 UTC, jaycorpstudios commented
@Poble04 no veo ningun push nuevo en este PR, no entendí muy bien tu comentario pero por favor deja de estar haciendo copias o reemplazando carpetas src. Si necesitas rescatar tus cambios siempre puedes crear un branch nuevo y hacer cherry pick de commits existentes. Sigo a la espera de que actualices este Pull Request o en su defecto declinar este y crear otro con un nuevo branch.

2019-04-05 02:46 UTC, closed without merging