Expo 005/dinamizar header tasks
TeifitV/ProyectoFinal pull request #10
Opened 2019-04-08 03:47 UTC by Jterraza

Dinamizar task header

2019-04-08 05:03 UTC, jaycorpstudios requested changes

2019-04-08 05:03 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +import { View , TouchableOpacity, StyleSheet, Text, Modal, Image ,category} from 'react-native';
para que necesitas esto? category no existe en 'react-native'

2019-04-08 05:03 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +            category: this.props.navigation.getParam(category,"Party"),
No necesitas definir la categoria en el estado, ya que una vez que inicie la pantalla no planeamos cambiar la categoria. esa esa la razon de ser del estado, datos que van a cambiar. En realidad para cambiar la categoria tenemos que regresar a la pantalla de categorias, en ese momento este componente muere.

2019-04-08 05:03 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +            category: this.props.navigation.getParam(category,"Party"),
Por cierto si vas a agregar una categoria como fallback, que sea una categoria que ya existe. Y debe ser en minusculas en este caso.

2019-04-08 05:03 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +        const API_BASE_URL= 'https://remindmeapi.jaycorpstudios.now.sh/tasks/';
`API_BASE_URL` debe estar definido en otro archivo de constantes o configuracion para toda la aplicación.

2019-04-08 05:03 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +    componentDidMount(){
Si ya vas a requerir las tareas como datos dinamicos, necesitas borrar las que existen actualmente en el estado.

```javascript
this.state = {
            tasks: [],
};
```

2019-04-08 23:04 UTC, Jterraza commented
Buenas tardes profesor acabo de subir mis cambios podria revisarme

2019-04-09 01:30 UTC, jaycorpstudios requested changes

2019-04-09 01:30 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +import {category} from 'react';
Para que necesitas este import? category no existe en la librería de react

2019-04-09 01:30 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +            category: this.props.navigation.getParam(category,'school'),
insisto que esto no lo necesitas en el state.

2019-04-09 01:30 UTC, jaycorpstudios commented on src/screens/Tasks/index.js
> +        const {category} = this.state;
Ya habíamos hablado de esto, no necesitas el category en el state, es mejor que lo definas aquí:
`const category = this.props.navigation.getParam(category,'school');`

2019-04-09 01:30 UTC, jaycorpstudios commented on src/shared/Helper.js
> +export default class Helper{
Para que necesitas este Helper? no veo que lo uses en ningún lado. Si no lo necesitas borralo, igual el archivo de `Constants.js` ya que solo se usa en este Helper.

2019-04-09 02:26 UTC, jaycorpstudios approved these changes

2019-04-09 02:32 UTC, merged