pantalla inicio modificada
TeifitV/ProyectoFinal pull request #3
Opened 2019-04-04 03:28 UTC by Jterraza

Se modifico la imagen de fondo de la pantalla principal

2019-04-04 03:48 UTC, jaycorpstudios requested changes
No necesitas todas las imagenes en este PR, sólo necesitas la imagen del fondo. por favor quita todas las que no son necesarias.

2019-04-04 03:48 UTC, jaycorpstudios commented on src/screens/Home/index.js
> +        <Image style={styles.logo} source={ require('./../../images/pattern.png') }></Image>
Por que estas cambiando esta imagen? el Logo se debe mantener.
Lo que debe cambiar en esta vista es que se agrega una imagen de fondo.

2019-04-04 03:48 UTC, jaycorpstudios commented on src/screens/Home/index.js
> +} 000
estos tres ceros van a hacer que la aplicación truene al momento de compilar.

2019-04-05 02:07 UTC, Jterraza commented
profe ya corregi lo que me dijo podria revisarme

2019-04-05 02:47 UTC, Jterraza commented
Modificar pantalla de inicio

2019-04-05 02:53 UTC, jaycorpstudios reviewed
Esta es la tarea mas sencilla de todas, debería tomarte máximo 10 min realizarla. Sin embargo no se si no estas prestando atención o que esta pasando. Voy a declinar tu Pull Request ya que no tiene sentido alguno. Necesito que hagas un nuevo branch y lo intentes de nuevo, una vez que tengas tus cambios listos:

1.- Prueba que funcionan y no rompes nada
2.- Asegurate que la parte visual se ve como en las especificaciones.
3.- Asegurate que solo estas modificando archivos que son necesarios para completar tu ticket.
4.- Abre tu Pull Request y mandame un mensaje para revisarlo.

2019-04-05 02:53 UTC, jaycorpstudios commented on package.json
> +    "pinkie-promise": "^2.0.1",
Para que necesitas esta dependencia?

2019-04-05 02:53 UTC, jaycorpstudios commented on src/components/TaskHeader/index.js
> +    List =[
Tengo entendido que esta tarea es solo para modificar la pantalla Home, no se que están haciendo estos cambios aquí.

2019-04-05 02:53 UTC, jaycorpstudios commented on src/screens/Home/index.js
> +        <Image style={stye.background} source={require('./../../images/pattern.png')}></Image>
Esto sigue estando mal, te comente anteriormente que necesitabas solamente envolver el componente en un BackgroundImage.

2019-04-05 02:54 UTC, closed without merging