Expo 007/agregar date picker
TeifitV/ProyectoFinal pull request #8
Opened 2019-04-06 18:06 UTC by julio13carbajal

Se creo el datepicker

2019-04-07 00:58 UTC, jaycorpstudios requested changes
En general bastante bien, solo dejé un par de comentarios que no te deberían más de 5 minutos modificar

2019-04-07 00:58 UTC, jaycorpstudios commented on src/components/TaskModal/index.js
> +            <Text style={styles.headerText}>   AGREGAR TAREA</Text >
Hay que eliminar los espacios innecesarios

2019-04-07 00:58 UTC, jaycorpstudios commented on src/components/TaskModal/index.js
> +
Lo mismo aquí, los espacios muertos hacen complejo de leer el código

2019-04-07 00:58 UTC, jaycorpstudios commented on src/components/TaskModal/index.js
> +                customStyles={{
Por favor extrae los Custom Styles a otro archivo, impórtalos aquí y solamente pasa la referencia

2019-04-07 05:32 UTC, julio13carbajal commented
Modificaciones listas.

2019-04-07 15:43 UTC, jaycorpstudios reviewed
Un par de cambios más, no probaste tu código, si compilas esto va a tronar. Mi duda es por que cerraste el Pull Request? Esto debe permanecer abierto hasta que se apruebe. Tu sigues subiendo cambios y yo revisando. Debes tener una opción para reabrirlo

2019-04-07 15:43 UTC, jaycorpstudios commented on src/components/TaskModal/DatePickerStyles.js
> +        backgroundColor: Colors.primaryColorDarker
Necesitas importar la referencia de Colors en este archivo o va a tronar al momento de compilar

2019-04-07 15:43 UTC, jaycorpstudios commented on src/components/TaskModal/DatePickerStyles.js
> +  const datePickerStyles from StyleSheet.create({
Esto está mal declarado: no se usa from sino =

2019-04-07 15:43 UTC, jaycorpstudios commented on src/components/TaskModal/DatePickerStyles.js
> +export default styles;
Estás exportando los styles por default lo cual está bien, sin embargo necesitas también exportar los datePickerStyles.

export default styles;
export datePickerStyles;

2019-04-07 23:21 UTC, jaycorpstudios requested changes
Ya casi, solo un par de detalles. Me doy cuenta que no estás comprobando que tus cambios funcionen. Debes asegurarte de eso o vas a tronar la aplicación del equipo y estaría incompleta e inoperable

2019-04-07 23:21 UTC, jaycorpstudios commented on src/components/TaskModal/DatePickerStyles.js
> +        borderBottomWidth: Platform.OS === 'ios' ? 2 : 0,
De donde sacaste la validación de Platform? No estamos haciendo distinciones de plataformas en este PR, necesitas o eliminarlo o incluir la librería en el archivo. Por favor prueba tus cambios antes de subirlos o vas a romper la aplicación

2019-04-07 23:21 UTC, jaycorpstudios commented on src/components/TaskModal/index.js
> +import DatePicker from 'react-native-datepicker';
Esta dependencia de react-native-datepicker debe de estar incluida en package.json de otra forma cuando alguien levante la aplicación va a tronar

2019-04-08 00:08 UTC, jaycorpstudios approved these changes
Excelente ya puedes hacer merge y comenzar el proceso de QA

2019-04-09 01:00 UTC, merged